kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ovs-node
  namespace: openshift-ovn-kubernetes
  annotations:
    kubernetes.io/description: |
      This daemonset launches  Open vSwitch per-node networking components.
    release.openshift.io/version: "{{.ReleaseVersion}}"
spec:
  selector:
    matchLabels:
      app: ovs-node
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ovs-node
        component: network
        type: infra
        openshift.io/component: network
        kubernetes.io/os: "linux"
    spec:
      serviceAccountName: ovn-kubernetes-node
      hostNetwork: true
      hostPID: true
      priorityClassName: "system-node-critical"
      # volumes in all containers:
      # (container) -> (host)
      # /etc/openvswitch -> /var/lib/openvswitch/etc - ovsdb system id
      # /var/lib/openvswitch -> /var/lib/openvswitch/data - ovsdb data
      # /run/openvswitch -> tmpfs - ovsdb sockets
      # /env -> configmap env-overrides - debug overrides
      containers:
      # ovsdb and ovs-vswitchd
      - name: ovs-daemons
        image: "{{.OvnImage}}"
        command:
        - /bin/bash
        - -c
        - |
          #!/bin/bash
          set -euo pipefail
          set -x
          if [[ -f /usr/bin/id ]]; then
            /usr/bin/id openvswitch
          else
            echo "id command not found"
          fi
          if [[ -d /run/openvswitch ]]; then
            echo "Found dir /run/openvswitch before chown"
            ls -al /run/openvswitch
          fi
          if [[ -d /var/run/openvswitch ]]; then
            echo "Found dir /var/run/openvswitch before chown"
            ls -al /var/run/openvswitch
          fi
          if [[ -f "/env/${K8S_NODE}" ]]; then
            set -o allexport
            source "/env/${K8S_NODE}"
            set +o allexport
          fi
          chown -R openvswitch:openvswitch /run/openvswitch
          chown -R openvswitch:openvswitch /etc/openvswitch
          if [[ -d /run/openvswitch ]]; then
            echo "Found dir /run/openvswitch after chown"
            ls -al /run/openvswitch
          fi
          if [[ -d /var/run/openvswitch ]]; then
            echo "Found dir /var/run/openvswitch after chown"
            ls -al /var/run/openvswitch
          fi
          if [[ -f /var/run/openvswitch/ovs-vswitchd.pid ]] ; then
            cat /var/run/openvswitch/ovs-vswitchd.pid
          fi
          if [[ -f /var/run/openvswitch/ovsdb-server.pid ]] ; then
            cat /var/run/openvswitch/ovsdb-server.pid
          fi
          function quit {
              # Don't allow ovs-vswitchd to clear datapath flows on exit
              kill -9 $(cat /var/run/openvswitch/ovs-vswitchd.pid 2>/dev/null) 2>/dev/null || true
              kill $(cat /var/run/openvswitch/ovsdb-server.pid 2>/dev/null) 2>/dev/null || true
              exit 0
          }
          trap quit SIGTERM
          chroot /host /bin/bash <<EOF
          set -x
          export SYSTEMD_IGNORE_CHROOT=yes
          echo "systemd ignore chroot now set to " \$SYSTEMD_IGNORE_CHROOT
          if [[ -d /run/openvswitch ]]; then
            echo "Found dir /run/openvswitch inside chroot"
            ls -al /run/openvswitch
          fi
          if [[ -d /var/run/openvswitch ]]; then
            echo "Found dir /var/run/openvswitch inside chroot"
            ls -al /var/run/openvswitch
          fi
          systemctl start ovsdb-server.service
          journalctl -xeu ovsdb-server.service --no-pager
          systemctl start openvswitch.service
          journalctl -xeu openvswitch --no-pager
          EOF
          # Need container up v0.0 just to see if host starts ovs and friends
          /usr/share/openvswitch/scripts/ovs-ctl start --ovs-user=openvswitch:openvswitch --system-id=random
          ovs-appctl vlog/set "file:${OVS_LOG_LEVEL}"
          /usr/share/openvswitch/scripts/ovs-ctl --protocol=udp --dport=6081 enable-protocol

          tail -F --pid=$(cat /var/run/openvswitch/ovs-vswitchd.pid) /var/log/openvswitch/ovs-vswitchd.log &
          tail -F --pid=$(cat /var/run/openvswitch/ovsdb-server.pid) /var/log/openvswitch/ovsdb-server.log &
          wait
        env:
        - name: OVS_LOG_LEVEL
          value: info
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: host-slash
          readOnly: false
        - mountPath: /var/run/openvswitch
          name: host-run-openvswitch
        - mountPath: /var/log/openvswitch
          name: var-log-openvswitch
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          exec:
            command:
            - /usr/share/openvswitch/scripts/ovs-ctl
            - status
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - /usr/share/openvswitch/scripts/ovs-ctl
            - status
          initialDelaySeconds: 15
          periodSeconds: 5
        terminationGracePeriodSeconds: 10

      nodeSelector:
        beta.kubernetes.io/os: "linux"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: network.operator.openshift.io/external-openvswitch
                operator: DoesNotExist        
      volumes:
      # used for iptables wrapper scripts
      - name: host-run-openvswitch
        hostPath:
          path: /run/openvswitch
      - name: var-log-openvswitch
        hostPath:
          path: /var/log/openvswitch
      - name: host-slash
        hostPath:
          path: /
      tolerations:
      - operator: "Exists"
